---
  # https://docs.ansible.com/ansible/latest/modules/apt_key_module.html
- name: Add key
  apt_key: keyserver=keyserver.ubuntu.com id=EA312927
  tags: install
  # https://docs.ansible.com/ansible/latest/modules/apt_repository_module.html
- name: Add repo
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install
  # https://docs.ansible.com/ansible/latest/modules/apt_module.html
- name: Install package
  apt: name=mongodb-org state=present
  tags: install
  # https://docs.ansible.com/ansible/latest/modules/systemd_module.html
- name: Enable service
  systemd: name=mongod enabled=yes state=started
  tags: install
