FROM ruby:2.3-alpine

RUN apk --no-cache add make=4.2.1 gcc libc-dev=6.4.0 ruby=2.5.1 ruby-bundler=2.5.1 ruby-dev=2.5.1 && \
RUN apk --no-cache add make gcc libc-dev \
  && rm -rf /var/cache/apk/* \
  && gem install bundler

ENV APP_HOME /app
RUN mkdir $APP_HOME

WORKDIR $APP_HOME
COPY Gemfile* $APP_HOME/
RUN bundle install \
  && rm -rf /root/.bundle

COPY . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
