{
 "title": "Telegraf Docker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Docker CPUs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_n_cpus" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_container_mem_usage" }
   ]
  },
  {
   "title": "Docker Containers",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_n_containers" },
    { "expr": "docker_n_containers_running" },
    { "expr": "docker_n_containers_stopped" }
   ]
  }
 ]
}