{
 "title": "UI_Service_Monitoring",
 "tags": [
  "ui",
  "service"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "UI http requests",
   "type": "graph",
   "description": "All HTTP Requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[2345].*\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP Requests with Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Response time 95th percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}