---
- name: Install Ruby & Bundler
  hosts: all
  become: true
  tasks:

  # https://docs.ansible.com/ansible/latest/modules/apt_module.html
  - name: Install Ruby/Bundler and dependencies
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
        - ruby-full
        - ruby-bundler
        - build-essential

